pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }
        stage('Deploy to Heroku') {
            steps {
                // Steps to deploy to Heroku
            }
        }
    }
}
